<?php
    return array(
        'name_site' => 'Marich News',
        'languagesList' => array('en', 'ua', 'ru'),
        'api_key' => '8a00eb9d39104bd481105224e378ecce',
        'categoryList' => array(
            'business',
            'entertainment',
            'general',
            'health',
            'science',
            'sports',
            'technology'
        ),
        'defaultCountry' => 'en',
        'countryList' => array(
            'United Arab Emirates' => 'ae',
            'Argentina' => 'ar',
            'Austria' => 'at',
            'Australia' => 'au',
            'Belgium' => 'be', 
            'Bulgaria' => 'bg',
            'Brazil' => 'br', 
            'Canada' => 'ca',
            'Switzerland' => 'ch',
            'China' => 'cn',
            'Colombia' => 'co',
            'Cuba' => 'cu',
            'Czechia' => 'cz',
            'Germany' => 'de',
            'Egypt' => 'eg',
            'France' => 'fr',
            'United Kingdom' => 'gb',
            'Greece' => 'gr',
            'Hong Kong' => 'hk',
            'Hungary' => 'hu',
            'Indonesia' => 'id',
            'Ireland' => 'ie',
            'Israel' => 'il',
            'India' => 'in',
            'Italy' => 'it',
            'Japan' => 'jp',
            'Korea' => 'kr',
            'Lithuania' => 'lt',
            'Latvia' => 'lv',
            'Morocco' => 'ma',
            'Mexico' => 'mx',
            'Malaysia' => 'my',
            'Nigeria' => 'ng',
            'Netherlands' => 'nl',
            'Norway' => 'no',
            'New Zealand' => 'nz',
            'Philippines' => 'ph',
            'Poland' => 'pl',
            'Portugal' => 'pt',
            'Romania' => 'ro',
            'Serbia' => 'rs',
            'Russia' => 'ru',
            'Saudi Arabia' => 'sa',
            'Sweden' => 'se',
            'Singapore' => 'sg',
            'Slovenia' => 'si',
            'Slovakia' => 'sk',
            'Thailand' => 'th',
            'Turkey' => 'tr',
            'Taiwan' => 'tw',
            'Ukraine' => 'ua',
            'United States' => 'us',
            'Venezuela' => 've',
            'South Africa' => 'za'
        )
    );
